name = "my-app"  # Replace "my-app" with the name of your project
type = "javascript"

[build]
command = "npm run pages:build"
directory = "out"

[env.production]
workers_dev = false
compatibility_date = "2024-08-01"  # Replace with the current date or your preferred date
